[target.aarch64-linux-android]
linker = "clang"

[env]
CC_aarch64_linux_android = "clang"
CXX_aarch64_linux_android = "clang++"
AR_aarch64_linux_android = "llvm-ar"
ORT_CACHE_DIR = { value = ".ort-cache", relative = true }
